apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logsearch.fullname" . }}
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    app: {{ include "logsearch.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "logsearch.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "logsearch.name" . }}
    spec:
      {{- if or .Values.image.pullSecrets .Values.imagePullSecret.create }}
      imagePullSecrets:
      {{- if .Values.image.pullSecrets }}
      {{- range .Values.image.pullSecrets }}
        - name: {{ . | quote }}
      {{- end }}
      {{- else }}
        - name: {{ .Values.imagePullSecret.name | quote }}
      {{- end }}
      {{- end }}
      containers:
        - name: logsearch
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
            - containerPort: 3001
          readinessProbe:
            httpGet:
              path: /api/config
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          env:
            - name: DATA_DIR
              value: "/app/proxy/data"
            - name: APP_VERSION
              value: {{ .Values.appVersion | default .Values.image.tag | quote }}
          {{- if .Values.envConfig.enabled }}
          envFrom:
            - configMapRef:
                name: {{ .Values.envConfig.name | quote }}
            {{- if .Values.envSecrets.enabled }}
            - secretRef:
                name: {{ .Values.envSecrets.name | quote }}
            {{- end }}
          {{- end }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: proxy-data
              mountPath: /app/proxy/data
      volumes:
        - name: proxy-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "logsearch.fullname" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
