{{- if .Values.imagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    app: {{ include "logsearch.name" . }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ .Values.imagePullSecret.registry }}": {
          "username": "{{ .Values.imagePullSecret.username }}",
          "password": "{{ .Values.imagePullSecret.password }}",
          "email": "{{ .Values.imagePullSecret.email }}",
          "auth": "{{ printf "%s:%s" .Values.imagePullSecret.username .Values.imagePullSecret.password | b64enc }}"
        }
      }
    }
{{- end }}
