{{- if .Values.admin.useSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.admin.secretName }}
  labels:
    app: {{ include "logsearch.name" . }}
type: Opaque
data:
  ADMIN_USER: {{ .Values.admin.user | b64enc }}
  ADMIN_PASS: {{ .Values.admin.pass | b64enc }}
{{- end }}
