{{- if .Values.opensearch.useSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.opensearch.secretName }}
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    app: {{ include "logsearch.name" . }}
type: Opaque
data:
  OPENSEARCH_USERNAME: {{ .Values.opensearch.username | b64enc }}
  OPENSEARCH_PASSWORD: {{ .Values.opensearch.password | b64enc }}
{{- end }}
