apiVersion: v1
kind: Service
metadata:
  name: {{ include "logsearch.fullname" . }}
  labels:
    app: {{ include "logsearch.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "logsearch.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
