apiVersion: v1
kind: Service
metadata:
  name: logsearch-app
  namespace: logging
  labels:
    app: logsearch
    component: app
spec:
  type: NodePort
  selector:
    app: logsearch
    component: app
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
