replicaCount: 1

namespace:
  name: "opensearch"
  create: true

image:
  repository: vkramkumar/opensearch-logsearch
  tag: v1
  pullPolicy: Always
  pullSecrets: []

appVersion: "uat"

imagePullSecret:
  create: true
  name: "logsearch-regcred"
  registry: "https://index.docker.io/v1/"
  username: "vkramkumar"
  password: "FFck70@123"
  email: "vkram.kumar@hotmail.com"

service:
  type: NodePort
  port: 9090
  nodePort: 30090

resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "2"
    memory: "1024Mi"

persistence:
  enabled: true
  size: 10Gi

opensearch:
  host: ""
  port: "9200"
  scheme: "http"
  insecureSSL: "false"
  username: "no_body"
  password: "no_body"
  useSecret: true
  secretName: "logsearch-opensearch"

admin:
  user: "admin"
  pass: "redhat"
  useSecret: true
  secretName: "logsearch-admin"

defaultIndexPattern: "mains"
authTokenTtlMinutes: "10080"

rbac:
  enabled: true
  targetNamespace: "opensearch"
  subjectName: "default"
  subjectNamespace: "default"
  roleName: "logsearch-secret-writer"
  bindingName: "logsearch-secret-writer"
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
